# Generated by Django 4.0.5 on 2022-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=150)),
                ('class_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('class_code', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'classrooms',
                'ordering': ['created_on'],
            },
        ),
    ]
