# Generated by Django 4.0.5 on 2022-06-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_code',
        ),
    ]
