# Generated by Django 4.0.5 on 2022-06-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_classroom_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
