# Generated by Django 4.0.5 on 2022-06-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_classroom_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': 'classrooms'},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='created_on',
        ),
    ]
